// app/operations/transaction/detention-entry/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetFooter,
} from "@/components/ui/sheet";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import {
  CalendarIcon,
  Save,
  RefreshCw,
  Search,
  Printer,
  FileText,
  Eye,
  X,
  Check,
  Truck,
  MapPin,
  User,
  Phone,
  Building,
  Clock,
  Edit,
  PlusCircle,
  Trash2,
  Package,
  Weight,
  FileSpreadsheet,
  Calculator,
  AlertCircle,
  Filter,
  ChevronLeft,
  ChevronRight,
  Plus,
  History,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Fuel,
  Receipt,
  Users,
  Wrench,
  CreditCard,
  PieChart,
  Navigation,
  Flag,
  Circle,
  Map,
  Route,
  ArrowLeftRight,
  Layers,
  GitMerge,
  RotateCcw,
  FileWarning,
  Shield,
  ClipboardList,
  Timer,
  AlertTriangle,
  Zap,
  Download,
  Upload,
  Settings,
  BarChart,
  LineChart,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { format } from "date-fns";

// Types
interface DetentionEntry {
  id: number;
  detentionId: string;
  manifestNo: string;
  vehicleNo: string;
  driverName: string;
  driverContact: string;
  origin: string;
  destination: string;
  scheduleArrivalDate: Date;
  scheduleArrivalTime: string;
  actualArrivalDate: Date;
  actualArrivalTime: string;
  detentionStartDate: Date;
  detentionStartTime: string;
  detentionEndDate: Date;
  detentionEndTime: string;
  totalDetentionHours: number;
  detentionRatePerHour: number;
  detentionAmount: number;
  reasonForDelay: string;
  delayCategory: "traffic" | "documentation" | "vehicle_issue" | "customer_delay" | "weather" | "other";
  responsibleParty: string;
  remarks: string;
  status: "pending" | "approved" | "rejected" | "paid";
  createdBy: string;
  createdAt: Date;
  approvedBy: string;
  approvedDate: Date;
  paymentDate: Date;
  paymentMode: string;
  transactionId: string;
  documents: string[];
  autoGenerated: boolean;
}

interface DetentionRule {
  id: number;
  ruleName: string;
  freeHours: number;
  ratePerHour: number;
  maxAmount: number;
  applicableVehicleTypes: string[];
  applicableRoutes: string[];
  active: boolean;
}

interface DetentionSummary {
  totalDetentions: number;
  totalAmount: number;
  pendingAmount: number;
  paidAmount: number;
  averageDelay: number;
}

// Options
const delayCategoryOptions = [
  { value: "traffic", label: "Traffic Congestion", icon: "🚗", color: "bg-orange-100 text-orange-700" },
  { value: "documentation", label: "Documentation Issue", icon: "📄", color: "bg-red-100 text-red-700" },
  { value: "vehicle_issue", label: "Vehicle Breakdown", icon: "🔧", color: "bg-yellow-100 text-yellow-700" },
  { value: "customer_delay", label: "Customer Delay", icon: "👥", color: "bg-purple-100 text-purple-700" },
  { value: "weather", label: "Weather Condition", icon: "🌧️", color: "bg-blue-100 text-blue-700" },
  { value: "other", label: "Other", icon: "📝", color: "bg-gray-100 text-gray-700" }
];

const responsiblePartyOptions = [
  "Transporter", "Customer", "Driver", "Loading Party", "Unloading Party", "Weather", "Government", "Other"
];

const statusOptions = [
  { value: "pending", label: "Pending", color: "bg-yellow-100 text-yellow-700" },
  { value: "approved", label: "Approved", color: "bg-green-100 text-green-700" },
  { value: "rejected", label: "Rejected", color: "bg-red-100 text-red-700" },
  { value: "paid", label: "Paid", color: "bg-blue-100 text-blue-700" }
];

const paymentModeOptions = ["Cash", "Cheque", "Bank Transfer", "UPI", "Credit Card"];
const locationOptions = [
  "DELHI", "MUMBAI", "BANGALORE", "CHENNAI", "KOLKATA", "AHMEDABAD", 
  "PUNE", "HYDERABAD", "JAIPUR", "LUCKNOW", "KANPUR", "NAGPUR"
];

// Sample Detention Rules
const sampleRules: DetentionRule[] = [
  { id: 1, ruleName: "Standard Rule", freeHours: 2, ratePerHour: 500, maxAmount: 10000, applicableVehicleTypes: ["Truck", "Container"], applicableRoutes: ["DELHI-MUMBAI", "MUMBAI-DELHI"], active: true },
  { id: 2, ruleName: "Premium Rule", freeHours: 1, ratePerHour: 750, maxAmount: 15000, applicableVehicleTypes: ["Trailer", "Tanker"], applicableRoutes: [], active: true },
  { id: 3, ruleName: "Local Rule", freeHours: 3, ratePerHour: 300, maxAmount: 5000, applicableVehicleTypes: ["Pickup", "Van"], applicableRoutes: [], active: true }
];

// Sample Detention Data
const generateSampleDetentions = (): DetentionEntry[] => {
  const detentions: DetentionEntry[] = [];
  const now = new Date();
  
  for (let i = 1; i <= 15; i++) {
    const scheduleDate = new Date(now);
    scheduleDate.setDate(now.getDate() - i);
    const actualDate = new Date(scheduleDate);
    actualDate.setHours(scheduleDate.getHours() + (3 + Math.floor(Math.random() * 8)));
    
    const hours = Math.floor((actualDate.getTime() - scheduleDate.getTime()) / (1000 * 60 * 60));
    const freeHours = 2;
    const rate = 500;
    const detentionHours = Math.max(0, hours - freeHours);
    const amount = detentionHours * rate;
    
    detentions.push({
      id: i,
      detentionId: `DET${String(i).padStart(4, "0")}`,
      manifestNo: `M${String(i).padStart(3, "0")}`,
      vehicleNo: `UP14AB${1000 + i}`,
      driverName: `Driver ${String.fromCharCode(64 + i)}`,
      driverContact: `98765432${String(10 + i).padStart(2, "0")}`,
      origin: locationOptions[i % locationOptions.length],
      destination: locationOptions[(i + 3) % locationOptions.length],
      scheduleArrivalDate: scheduleDate,
      scheduleArrivalTime: "10:00",
      actualArrivalDate: actualDate,
      actualArrivalTime: `${13 + (i % 6)}:${(i * 15) % 60}`,
      detentionStartDate: scheduleDate,
      detentionStartTime: "12:00",
      detentionEndDate: actualDate,
      detentionEndTime: `${15 + (i % 8)}:00`,
      totalDetentionHours: detentionHours,
      detentionRatePerHour: rate,
      detentionAmount: amount,
      reasonForDelay: delayCategoryOptions[i % 6].label,
      delayCategory: delayCategoryOptions[i % 6].value as any,
      responsibleParty: responsiblePartyOptions[i % 8],
      remarks: `Auto-generated detention entry for manifest ${`M${String(i).padStart(3, "0")}`}`,
      status: i % 4 === 0 ? "pending" : i % 4 === 1 ? "approved" : i % 4 === 2 ? "rejected" : "paid",
      createdBy: "System",
      createdAt: scheduleDate,
      approvedBy: i % 2 === 0 ? "Admin" : "",
      approvedDate: i % 2 === 0 ? new Date(scheduleDate.getTime() + 86400000) : new Date(),
      paymentDate: i % 4 === 3 ? new Date(scheduleDate.getTime() + 172800000) : new Date(),
      paymentMode: i % 4 === 3 ? paymentModeOptions[i % 5] : "",
      transactionId: i % 4 === 3 ? `TXN${String(i).padStart(6, "0")}` : "",
      documents: [],
      autoGenerated: true,
    });
  }
  return detentions;
};

export default function DetentionEntry() {
  // Main state
  const [activeTab, setActiveTab] = useState<"view" | "rules" | "summary">("view");
  const [detentions, setDetentions] = useState<DetentionEntry[]>([]);
  const [rules, setRules] = useState<DetentionRule[]>(sampleRules);
  const [loading, setLoading] = useState(false);
  const [selectedDetention, setSelectedDetention] = useState<DetentionEntry | null>(null);
  
  // Filter state
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [searchStatus, setSearchStatus] = useState<string>("all");
  const [searchFromDate, setSearchFromDate] = useState<Date | undefined>();
  const [searchToDate, setSearchToDate] = useState<Date | undefined>();
  const [searchVehicle, setSearchVehicle] = useState<string>("");
  const [currentPage, setCurrentPage] = useState<number>(1);
  const itemsPerPage: number = 10;
  
  // Dialog states
  const [isDetailsDialogOpen, setIsDetailsDialogOpen] = useState(false);
  const [isApproveDialogOpen, setIsApproveDialogOpen] = useState(false);
  const [isRejectDialogOpen, setIsRejectDialogOpen] = useState(false);
  const [isRuleDialogOpen, setIsRuleDialogOpen] = useState(false);
  const [approveRemarks, setApproveRemarks] = useState("");
  const [rejectReason, setRejectReason] = useState("");
  
  // Rule form state
  const [editRuleId, setEditRuleId] = useState<number | null>(null);
  const [ruleName, setRuleName] = useState("");
  const [freeHours, setFreeHours] = useState(2);
  const [ratePerHour, setRatePerHour] = useState(500);
  const [maxAmount, setMaxAmount] = useState(10000);
  const [applicableVehicleTypes, setApplicableVehicleTypes] = useState<string[]>([]);
  const [applicableRoutes, setApplicableRoutes] = useState<string[]>([]);
  const [ruleActive, setRuleActive] = useState(true);

  // Load data on mount
  useEffect(() => {
    generateDetentions();
  }, []);

  const generateDetentions = () => {
    setLoading(true);
    setTimeout(() => {
      const newDetentions = generateSampleDetentions();
      setDetentions(newDetentions);
      setLoading(false);
    }, 500);
  };

  const handleRegenerate = () => {
    if (confirm("This will regenerate all detention entries. Are you sure?")) {
      generateDetentions();
    }
  };

  const handleViewDetails = (detention: DetentionEntry) => {
    setSelectedDetention(detention);
    setIsDetailsDialogOpen(true);
  };

  const handleApprove = () => {
    if (!selectedDetention) return;
    
    const updatedDetentions = detentions.map(d => 
      d.id === selectedDetention.id 
        ? { 
            ...d, 
            status: "approved" as const, 
            approvedBy: "MAYANK.GRLOGISTICS@GMAIL.COM",
            approvedDate: new Date(),
            remarks: approveRemarks || d.remarks
          }
        : d
    );
    setDetentions(updatedDetentions);
    setIsApproveDialogOpen(false);
    setApproveRemarks("");
    setSelectedDetention(null);
    alert(`Detention ${selectedDetention.detentionId} approved successfully!`);
  };

  const handleReject = () => {
    if (!selectedDetention) return;
    
    const updatedDetentions = detentions.map(d => 
      d.id === selectedDetention.id 
        ? { ...d, status: "rejected" as const, remarks: rejectReason }
        : d
    );
    setDetentions(updatedDetentions);
    setIsRejectDialogOpen(false);
    setRejectReason("");
    setSelectedDetention(null);
    alert(`Detention ${selectedDetention.detentionId} rejected!`);
  };

  const handleMarkAsPaid = (detention: DetentionEntry) => {
    if (confirm(`Mark detention ${detention.detentionId} as paid?`)) {
      const updatedDetentions = detentions.map(d => 
        d.id === detention.id 
          ? { ...d, status: "paid" as const, paymentDate: new Date() }
          : d
      );
      setDetentions(updatedDetentions);
      alert(`Detention ${detention.detentionId} marked as paid!`);
    }
  };

  // Rule Management
  const handleAddRule = () => {
    if (!ruleName) {
      alert("Please enter rule name");
      return;
    }
    
    const newRule: DetentionRule = {
      id: editRuleId || Date.now(),
      ruleName,
      freeHours,
      ratePerHour,
      maxAmount,
      applicableVehicleTypes,
      applicableRoutes,
      active: ruleActive,
    };
    
    if (editRuleId) {
      setRules(rules.map(r => r.id === editRuleId ? newRule : r));
      alert("Rule updated successfully!");
    } else {
      setRules([...rules, newRule]);
      alert("Rule added successfully!");
    }
    
    resetRuleForm();
    setIsRuleDialogOpen(false);
  };

  const handleEditRule = (rule: DetentionRule) => {
    setEditRuleId(rule.id);
    setRuleName(rule.ruleName);
    setFreeHours(rule.freeHours);
    setRatePerHour(rule.ratePerHour);
    setMaxAmount(rule.maxAmount);
    setApplicableVehicleTypes(rule.applicableVehicleTypes);
    setApplicableRoutes(rule.applicableRoutes);
    setRuleActive(rule.active);
    setIsRuleDialogOpen(true);
  };

  const handleDeleteRule = (id: number) => {
    if (confirm("Are you sure you want to delete this rule?")) {
      setRules(rules.filter(r => r.id !== id));
      alert("Rule deleted successfully!");
    }
  };

  const resetRuleForm = () => {
    setRuleName("");
    setFreeHours(2);
    setRatePerHour(500);
    setMaxAmount(10000);
    setApplicableVehicleTypes([]);
    setApplicableRoutes([]);
    setRuleActive(true);
    setEditRuleId(null);
  };

  // Filter functions
  const getFilteredDetentions = () => {
    let filtered = [...detentions];
    
    if (searchTerm) {
      filtered = filtered.filter(d => 
        d.detentionId.toLowerCase().includes(searchTerm.toLowerCase()) ||
        d.manifestNo.toLowerCase().includes(searchTerm.toLowerCase()) ||
        d.vehicleNo.toLowerCase().includes(searchTerm.toLowerCase()) ||
        d.driverName.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }
    
    if (searchStatus !== "all") {
      filtered = filtered.filter(d => d.status === searchStatus);
    }
    
    if (searchVehicle) {
      filtered = filtered.filter(d => d.vehicleNo.toLowerCase().includes(searchVehicle.toLowerCase()));
    }
    
    if (searchFromDate) {
      filtered = filtered.filter(d => d.createdAt >= searchFromDate!);
    }
    
    if (searchToDate) {
      filtered = filtered.filter(d => d.createdAt <= searchToDate!);
    }
    
    return filtered;
  };

  const handleSearch = () => {
    setCurrentPage(1);
  };

  const handleClearSearch = () => {
    setSearchTerm("");
    setSearchStatus("all");
    setSearchVehicle("");
    setSearchFromDate(undefined);
    setSearchToDate(undefined);
    setCurrentPage(1);
  };

  // Summary calculations
  const summary: DetentionSummary = {
    totalDetentions: detentions.length,
    totalAmount: detentions.reduce((sum, d) => sum + d.detentionAmount, 0),
    pendingAmount: detentions.filter(d => d.status === "pending").reduce((sum, d) => sum + d.detentionAmount, 0),
    paidAmount: detentions.filter(d => d.status === "paid").reduce((sum, d) => sum + d.detentionAmount, 0),
    averageDelay: detentions.length > 0 ? detentions.reduce((sum, d) => sum + d.totalDetentionHours, 0) / detentions.length : 0,
  };

  // Pagination
  const filteredDetentions = getFilteredDetentions();
  const totalPages = Math.ceil(filteredDetentions.length / itemsPerPage);
  const paginatedDetentions = filteredDetentions.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
  const goToPage = (page: number) => setCurrentPage(Math.max(1, Math.min(page, totalPages)));

  const getStatusBadge = (status: string) => {
    const config = statusOptions.find(s => s.value === status);
    return <Badge className={config?.color || "bg-gray-100"}>{config?.label || status}</Badge>;
  };

  const getDelayCategoryBadge = (category: string) => {
    const config = delayCategoryOptions.find(c => c.value === category);
    return <Badge className={config?.color || "bg-gray-100"}>{config?.icon} {config?.label}</Badge>;
  };

  // Export to CSV
  const handleExportCSV = () => {
    const headers = ["Detention ID", "Manifest #", "Vehicle #", "Driver", "Schedule Date", "Actual Date", "Delay Hours", "Amount", "Status"];
    const rows = filteredDetentions.map(d => [
      d.detentionId, d.manifestNo, d.vehicleNo, d.driverName,
      format(d.scheduleArrivalDate, "dd-MM-yyyy"),
      format(d.actualArrivalDate, "dd-MM-yyyy"),
      d.totalDetentionHours.toString(),
      d.detentionAmount.toString(),
      d.status
    ]);
    
    const csvContent = [headers, ...rows].map(row => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `detention_report_${format(new Date(), "dd-MM-yyyy")}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    alert("Report exported successfully!");
  };

  return (
    <div className="space-y-4 p-3 md:p-4 bg-gradient-to-br from-slate-50 to-slate-100 min-h-screen">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm border p-4">
        <div className="flex flex-wrap justify-between items-start gap-3">
          <div>
            <div className="flex items-center gap-2">
              <Timer className="h-5 w-5 text-blue-600" />
              <h1 className="text-xl md:text-2xl font-bold text-gray-800">DETENTION ENTRY</h1>
              <Badge className="bg-blue-100 text-blue-700 text-[10px] ml-2">Auto-Generated</Badge>
            </div>
            <div className="mt-2 flex flex-wrap gap-x-6 gap-y-1 text-xs text-gray-500">
              <span>🏢 Company: GOLDEN ROADWAYS & LOGISTICS PVT LTD</span>
              <span>👤 Login: MAYANK.GRLOGISTICS@GMAIL.COM</span>
              <span>📍 Branch: CORPORATE OFFICE</span>
              <span>📅 Financial Year: 2026-2027</span>
            </div>
          </div>
          <div className="flex gap-2">
            <Button onClick={handleRegenerate} variant="outline" size="sm" className="h-8 text-xs">
              <RefreshCw className="mr-1 h-3.5 w-3.5" />
              Regenerate
            </Button>
            <Button onClick={handleExportCSV} variant="outline" size="sm" className="h-8 text-xs">
              <Download className="mr-1 h-3.5 w-3.5" />
              Export CSV
            </Button>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <Card className="bg-gradient-to-r from-blue-500 to-blue-600 text-white">
          <CardContent className="p-3"><div className="flex justify-between items-center"><div><p className="text-[10px] opacity-90">Total Detentions</p><p className="text-2xl font-bold">{summary.totalDetentions}</p></div><Timer className="h-8 w-8 opacity-80" /></div></CardContent>
        </Card>
        <Card className="bg-gradient-to-r from-green-500 to-green-600 text-white">
          <CardContent className="p-3"><div className="flex justify-between items-center"><div><p className="text-[10px] opacity-90">Total Amount</p><p className="text-2xl font-bold">₹{summary.totalAmount.toLocaleString()}</p></div><DollarSign className="h-8 w-8 opacity-80" /></div></CardContent>
        </Card>
        <Card className="bg-gradient-to-r from-yellow-500 to-yellow-600 text-white">
          <CardContent className="p-3"><div className="flex justify-between items-center"><div><p className="text-[10px] opacity-90">Pending Amount</p><p className="text-2xl font-bold">₹{summary.pendingAmount.toLocaleString()}</p></div><Clock className="h-8 w-8 opacity-80" /></div></CardContent>
        </Card>
        <Card className="bg-gradient-to-r from-purple-500 to-purple-600 text-white">
          <CardContent className="p-3"><div className="flex justify-between items-center"><div><p className="text-[10px] opacity-90">Paid Amount</p><p className="text-2xl font-bold">₹{summary.paidAmount.toLocaleString()}</p></div><CheckCircle className="h-8 w-8 opacity-80" /></div></CardContent>
        </Card>
        <Card className="bg-gradient-to-r from-orange-500 to-orange-600 text-white">
          <CardContent className="p-3"><div className="flex justify-between items-center"><div><p className="text-[10px] opacity-90">Avg Delay (Hrs)</p><p className="text-2xl font-bold">{summary.averageDelay.toFixed(1)}</p></div><AlertTriangle className="h-8 w-8 opacity-80" /></div></CardContent>
        </Card>
      </div>

      {/* Main Tabs */}
      <div className="flex border-b bg-white rounded-t-lg">
        <button onClick={() => setActiveTab("view")} className={cn("px-6 py-2.5 text-sm font-medium transition-all rounded-t-lg flex items-center gap-2", activeTab === "view" ? "bg-blue-600 text-white shadow-md" : "text-gray-600 hover:text-gray-800 hover:bg-gray-100")}><Eye className="h-4 w-4" />View Detentions</button>
        <button onClick={() => setActiveTab("rules")} className={cn("px-6 py-2.5 text-sm font-medium transition-all rounded-t-lg flex items-center gap-2", activeTab === "rules" ? "bg-green-600 text-white shadow-md" : "text-gray-600 hover:text-gray-800 hover:bg-gray-100")}><Settings className="h-4 w-4" />Detention Rules</button>
        <button onClick={() => setActiveTab("summary")} className={cn("px-6 py-2.5 text-sm font-medium transition-all rounded-t-lg flex items-center gap-2", activeTab === "summary" ? "bg-purple-600 text-white shadow-md" : "text-gray-600 hover:text-gray-800 hover:bg-gray-100")}><BarChart className="h-4 w-4" />Summary</button>
      </div>

      {/* View Detentions Tab */}
      {activeTab === "view" && (
        <>
          <Card><CardHeader className="pb-3"><CardTitle className="text-[11px] font-semibold flex items-center gap-2"><Search className="h-3.5 w-3.5" />Search Detentions</CardTitle></CardHeader>
          <CardContent><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3">
            <Input placeholder="Detention ID, Manifest #, Vehicle #" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="h-8 text-xs" />
            <Select value={searchStatus} onValueChange={setSearchStatus}><SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="approved">Approved</SelectItem><SelectItem value="rejected">Rejected</SelectItem><SelectItem value="paid">Paid</SelectItem></SelectContent></Select>
            <Input placeholder="Vehicle #" value={searchVehicle} onChange={(e) => setSearchVehicle(e.target.value)} className="h-8 text-xs" />
            <Popover><PopoverTrigger asChild><Button variant="outline" className="h-8 text-xs justify-start"><CalendarIcon className="mr-1 h-3 w-3" />{searchFromDate ? format(searchFromDate, "dd-MM-yyyy") : "From Date"}</Button></PopoverTrigger><PopoverContent><Calendar mode="single" selected={searchFromDate} onSelect={setSearchFromDate} /></PopoverContent></Popover>
            <Popover><PopoverTrigger asChild><Button variant="outline" className="h-8 text-xs justify-start"><CalendarIcon className="mr-1 h-3 w-3" />{searchToDate ? format(searchToDate, "dd-MM-yyyy") : "To Date"}</Button></PopoverTrigger><PopoverContent><Calendar mode="single" selected={searchToDate} onSelect={setSearchToDate} /></PopoverContent></Popover>
            <div className="flex gap-2"><Button onClick={handleSearch} size="sm" className="h-8 text-xs bg-blue-600"><Search className="h-3 w-3 mr-1" />Search</Button><Button onClick={handleClearSearch} variant="outline" size="sm" className="h-8 text-xs"><RefreshCw className="h-3 w-3" /></Button></div>
          </div></CardContent></Card>

          <Card><CardHeader className="pb-2"><div className="flex justify-between items-center"><div className="gap-2 w-full">
                        <Table className="text-gray-500" />
                        <h3 className="text-[15px] font-semibold text-gray-800">Detention Entries</h3></div><div className="text-[10px] text-gray-500">Total: {filteredDetentions.length} records | Auto-Generated</div></div></CardHeader>
          <CardContent><div className="rounded-md border overflow-x-auto"><div className="min-w-[1100px]"><Table><TableHeader><TableRow className="bg-gray-50"><TableHead className="text-[11px] w-12">#</TableHead><TableHead className="text-[11px]">Detention ID</TableHead><TableHead className="text-[11px]">Manifest #</TableHead><TableHead className="text-[11px]">Vehicle #</TableHead><TableHead className="text-[11px]">Driver</TableHead><TableHead className="text-[11px]">Schedule Date</TableHead><TableHead className="text-[11px]">Actual Date</TableHead><TableHead className="text-[11px] text-center">Delay (Hrs)</TableHead><TableHead className="text-[11px] text-right">Amount</TableHead><TableHead className="text-[11px]">Status</TableHead><TableHead className="text-[11px] w-32">Actions</TableHead></TableRow></TableHeader>
          <TableBody>{paginatedDetentions.map((d, idx) => (<TableRow key={d.id}><TableCell className="text-center text-xs">{(currentPage-1)*itemsPerPage+idx+1}</TableCell><TableCell className="font-mono text-xs">{d.detentionId}</TableCell><TableCell className="text-xs">{d.manifestNo}</TableCell><TableCell className="text-xs">{d.vehicleNo}</TableCell><TableCell className="text-xs">{d.driverName}</TableCell><TableCell className="text-xs">{format(d.scheduleArrivalDate, "dd-MM-yyyy")}</TableCell><TableCell className="text-xs">{format(d.actualArrivalDate, "dd-MM-yyyy")}</TableCell><TableCell className="text-center text-xs font-semibold">{d.totalDetentionHours}</TableCell><TableCell className="text-right text-xs">₹{d.detentionAmount.toLocaleString()}</TableCell><TableCell>{getStatusBadge(d.status)}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => handleViewDetails(d)} className="h-7 w-7 p-0 text-blue-500"><Eye className="h-3.5 w-3.5" /></Button>{d.status === "pending" && <Button variant="ghost" size="sm" onClick={() => { setSelectedDetention(d); setIsApproveDialogOpen(true); }} className="h-7 w-7 p-0 text-green-500"><Check className="h-3.5 w-3.5" /></Button>}{d.status === "approved" && <Button variant="ghost" size="sm" onClick={() => handleMarkAsPaid(d)} className="h-7 w-7 p-0 text-blue-500"><DollarSign className="h-3.5 w-3.5" /></Button>}</div></TableCell></TableRow>))}</TableBody></Table></div></div>
          {totalPages > 1 && (<div className="flex justify-center gap-1 mt-4"><Button variant="outline" size="sm" onClick={() => goToPage(currentPage-1)} disabled={currentPage===1} className="h-7 text-[10px]">Previous</Button><span className="px-3 py-1 text-[10px]">Page {currentPage} of {totalPages}</span><Button variant="outline" size="sm" onClick={() => goToPage(currentPage+1)} disabled={currentPage===totalPages} className="h-7 text-[10px]">Next</Button></div>)}</CardContent></Card>
        </>
      )}

      {/* Detention Rules Tab */}
      {activeTab === "rules" && (
        <>
          <div className="flex justify-end"><Button onClick={() => { resetRuleForm(); setIsRuleDialogOpen(true); }} size="sm" className="h-8 text-xs bg-green-600"><Plus className="mr-1 h-3.5 w-3.5" />Add Rule</Button></div>
          <Card><CardHeader className="pb-2"><div className="flex justify-between items-center"><div className="flex items-center gap-2"><Settings className="h-3.5 w-3.5 text-gray-500" /><h3 className="text-[15px] font-semibold">Detention Calculation Rules</h3></div><div className="text-[10px] text-gray-500">Total: {rules.length} rules</div></div></CardHeader>
          <CardContent><div className="rounded-md border overflow-x-auto"><div className="min-w-[800px]"><Table><TableHeader><TableRow className="bg-gray-50"><TableHead className="text-[11px] w-12">#</TableHead><TableHead className="text-[11px]">Rule Name</TableHead><TableHead className="text-[11px] text-center">Free Hours</TableHead><TableHead className="text-[11px] text-right">Rate/Hour</TableHead><TableHead className="text-[11px] text-right">Max Amount</TableHead><TableHead className="text-[11px]">Vehicle Types</TableHead><TableHead className="text-[11px]">Status</TableHead><TableHead className="text-[11px] w-24">Actions</TableHead></TableRow></TableHeader>
          <TableBody>{rules.map((rule, idx) => (<TableRow key={rule.id}><TableCell className="text-center text-xs">{idx+1}</TableCell><TableCell className="text-xs font-medium">{rule.ruleName}</TableCell><TableCell className="text-center text-xs">{rule.freeHours} hrs</TableCell><TableCell className="text-right text-xs">₹{rule.ratePerHour}</TableCell><TableCell className="text-right text-xs">₹{rule.maxAmount.toLocaleString()}</TableCell><TableCell className="text-xs">{rule.applicableVehicleTypes.length > 0 ? rule.applicableVehicleTypes.join(", ") : "All"}</TableCell><TableCell>{rule.active ? <Badge className="bg-green-100 text-green-700">Active</Badge> : <Badge className="bg-gray-100 text-gray-700">Inactive</Badge>}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => handleEditRule(rule)} className="h-7 w-7 p-0 text-blue-500"><Edit className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => handleDeleteRule(rule.id)} className="h-7 w-7 p-0 text-red-500"><Trash2 className="h-3.5 w-3.5" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div></div></CardContent></Card>
        </>
      )}

      {/* Summary Tab */}
      {activeTab === "summary" && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card><CardHeader><CardTitle className="text-sm font-semibold">Detention Summary by Status</CardTitle></CardHeader><CardContent><div className="space-y-3">{statusOptions.map(status => { const count = detentions.filter(d => d.status === status.value).length; const amount = detentions.filter(d => d.status === status.value).reduce((s, d) => s + d.detentionAmount, 0); return (<div key={status.value} className="flex justify-between items-center p-2 border-b"><div className="flex items-center gap-2">{getStatusBadge(status.value)}<span className="text-sm">{count} entries</span></div><div className="text-right"><span className="text-sm font-medium">₹{amount.toLocaleString()}</span></div></div>); })}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm font-semibold">Delay Analysis by Category</CardTitle></CardHeader><CardContent><div className="space-y-3">{delayCategoryOptions.map(cat => { const count = detentions.filter(d => d.delayCategory === cat.value).length; const avgDelay = detentions.filter(d => d.delayCategory === cat.value).reduce((s, d) => s + d.totalDetentionHours, 0) / (count || 1); return (<div key={cat.value} className="flex justify-between items-center p-2 border-b"><div className="flex items-center gap-2"><span className="text-lg">{cat.icon}</span><span className="text-sm">{cat.label}</span></div><div className="text-right"><span className="text-sm font-medium">{count} detentions</span><p className="text-xs text-gray-500">Avg Delay: {avgDelay.toFixed(1)} hrs</p></div></div>); })}</div></CardContent></Card>
        </div>
      )}

      {/* Detention Details Dialog */}
      <Dialog open={isDetailsDialogOpen} onOpenChange={setIsDetailsDialogOpen}>
        <DialogContent className="max-w-2xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><Timer className="h-5 w-5 text-blue-600" />Detention Details - {selectedDetention?.detentionId}</DialogTitle></DialogHeader>
        {selectedDetention && (<div className="space-y-4"><div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">Manifest #</Label><p className="text-sm font-medium">{selectedDetention.manifestNo}</p></div><div><Label className="text-xs">Vehicle #</Label><p className="text-sm font-medium">{selectedDetention.vehicleNo}</p></div><div><Label className="text-xs">Driver Name</Label><p className="text-sm">{selectedDetention.driverName}</p></div><div><Label className="text-xs">Driver Contact</Label><p className="text-sm">{selectedDetention.driverContact}</p></div><div><Label className="text-xs">Route</Label><p className="text-sm">{selectedDetention.origin} → {selectedDetention.destination}</p></div><div><Label className="text-xs">Delay Category</Label><div>{getDelayCategoryBadge(selectedDetention.delayCategory)}</div></div><div><Label className="text-xs">Schedule Arrival</Label><p className="text-sm">{format(selectedDetention.scheduleArrivalDate, "dd-MM-yyyy")} {selectedDetention.scheduleArrivalTime}</p></div><div><Label className="text-xs">Actual Arrival</Label><p className="text-sm">{format(selectedDetention.actualArrivalDate, "dd-MM-yyyy")} {selectedDetention.actualArrivalTime}</p></div><div><Label className="text-xs">Total Detention Hours</Label><p className="text-xl font-bold text-red-600">{selectedDetention.totalDetentionHours} hrs</p></div><div><Label className="text-xs">Detention Amount</Label><p className="text-xl font-bold text-green-600">₹{selectedDetention.detentionAmount.toLocaleString()}</p></div><div><Label className="text-xs">Responsible Party</Label><p className="text-sm">{selectedDetention.responsibleParty}</p></div><div><Label className="text-xs">Status</Label><div>{getStatusBadge(selectedDetention.status)}</div></div><div className="col-span-2"><Label className="text-xs">Reason for Delay</Label><p className="text-sm bg-gray-50 p-2 rounded">{selectedDetention.reasonForDelay}</p></div><div className="col-span-2"><Label className="text-xs">Remarks</Label><p className="text-sm">{selectedDetention.remarks}</p></div></div><div className="text-xs text-gray-400 border-t pt-2 mt-2">Auto-Generated: {selectedDetention.autoGenerated ? "Yes" : "No"} | Created: {format(selectedDetention.createdAt, "dd-MM-yyyy HH:mm")}</div></div>)}
        <DialogFooter><Button variant="outline" onClick={() => setIsDetailsDialogOpen(false)}>Close</Button></DialogFooter></DialogContent>
      </Dialog>

      {/* Approve Dialog */}
      <Dialog open={isApproveDialogOpen} onOpenChange={setIsApproveDialogOpen}><DialogContent><DialogHeader><DialogTitle>Approve Detention</DialogTitle><DialogDescription>Approve detention for {selectedDetention?.detentionId}</DialogDescription></DialogHeader><div className="space-y-4"><div className="p-3 bg-gray-50 rounded-md"><p className="text-sm"><span className="font-medium">Amount:</span> ₹{selectedDetention?.detentionAmount.toLocaleString()}</p><p className="text-sm"><span className="font-medium">Delay Hours:</span> {selectedDetention?.totalDetentionHours} hrs</p></div><div><Label className="text-sm">Approval Remarks</Label><Textarea value={approveRemarks} onChange={(e) => setApproveRemarks(e.target.value)} rows={2} placeholder="Enter approval remarks..." /></div></div><DialogFooter><Button variant="outline" onClick={() => setIsApproveDialogOpen(false)}>Cancel</Button><Button onClick={handleApprove} className="bg-green-600">Approve</Button></DialogFooter></DialogContent></Dialog>

      {/* Reject Dialog */}
      <Dialog open={isRejectDialogOpen} onOpenChange={setIsRejectDialogOpen}><DialogContent><DialogHeader><DialogTitle>Reject Detention</DialogTitle><DialogDescription>Reject detention for {selectedDetention?.detentionId}</DialogDescription></DialogHeader><div><Label className="text-sm">Rejection Reason *</Label><Textarea value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} rows={2} placeholder="Enter rejection reason..." /></div><DialogFooter><Button variant="outline" onClick={() => setIsRejectDialogOpen(false)}>Cancel</Button><Button onClick={handleReject} variant="destructive">Reject</Button></DialogFooter></DialogContent></Dialog>

      {/* Rule Dialog */}
      <Dialog open={isRuleDialogOpen} onOpenChange={setIsRuleDialogOpen}><DialogContent><DialogHeader><DialogTitle>{editRuleId ? "Edit Rule" : "Add Rule"}</DialogTitle></DialogHeader><div className="space-y-4"><div><Label className="text-sm">Rule Name *</Label><Input value={ruleName} onChange={(e) => setRuleName(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><Label className="text-sm">Free Hours</Label><Input type="number" value={freeHours} onChange={(e) => setFreeHours(Number(e.target.value))} /></div><div><Label className="text-sm">Rate Per Hour (₹)</Label><Input type="number" value={ratePerHour} onChange={(e) => setRatePerHour(Number(e.target.value))} /></div></div><div><Label className="text-sm">Max Amount (₹)</Label><Input type="number" value={maxAmount} onChange={(e) => setMaxAmount(Number(e.target.value))} /></div><div><div className="flex items-center gap-2"><input type="checkbox" checked={ruleActive} onChange={(e) => setRuleActive(e.target.checked)} className="h-4 w-4" /><Label className="text-sm cursor-pointer">Active</Label></div></div></div><DialogFooter><Button variant="outline" onClick={() => setIsRuleDialogOpen(false)}>Cancel</Button><Button onClick={handleAddRule} className="bg-blue-600">{editRuleId ? "Update" : "Add"}</Button></DialogFooter></DialogContent></Dialog>
    </div>
  );
}

// Missing imports
import { CheckCircle } from "lucide-react";